# Generated by Django 3.2.3 on 2021-07-31 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_x', models.PositiveIntegerField()),
                ('size_y', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pos_x', models.PositiveIntegerField()),
                ('pos_y', models.PositiveIntegerField()),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universe.galaxy')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('diameter', models.FloatField()),
                ('star_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universe.starsystem')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('diameter', models.FloatField()),
                ('live', models.BooleanField(default=False)),
                ('star_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universe.starsystem')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('diameter', models.FloatField()),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universe.planet')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
