# Generated by Django 3.2.3 on 2021-07-31 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starsystem',
            name='galaxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='universe.galaxy'),
        ),
    ]
