# Generated by Django 3.2.3 on 2021-07-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowling', '0002_rename_row_personalframe_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalthrow',
            old_name='row',
            new_name='frame',
        ),
    ]
